// Generated by CoffeeScript 1.6.3
(function() {
  var Aggregate, ConcreteAggregate, ConcreteIterator, Iterator, List, Mimosas, Observer, Subject, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Mimosas = {};

  Mimosas.Observer = Observer = (function() {
    function Observer() {}

    Observer.prototype.changed = function(theChangedSubject) {};

    return Observer;

  })();

  Mimosas.List = List = (function() {
    function List() {
      this.items = [];
      this.objects = {};
    }

    List.prototype.count = function() {
      return this.items.length;
    };

    List.prototype.getByIndex = function(index) {
      if (index >= this.count()) {
        throw new Error('ArrayOutOfBoundsException');
      }
      if (index < 0) {
        throw new Error('ArrayOutOfBoundsException');
      }
      return this.objects[this.items[index]];
    };

    List.prototype.get = function(pointer) {
      return this.objects[pointer];
    };

    List.prototype.first = function() {
      return this.objects[this.items[0]];
    };

    List.prototype.last = function() {
      return this.objects[this.items[this.items.length - 1]];
    };

    List.prototype.append = function(item) {
      var pointer;
      if (item.__POINTER__ == null) {
        throw new Error('NullPointerException');
      }
      pointer = item.__POINTER__;
      this.items.push(pointer);
      return this.objects[pointer] = item;
    };

    List.prototype.remove = function(pointer) {
      var i, index, item, _i, _len, _ref;
      if (pointer == null) {
        throw new Error('ArgumentException');
      }
      if (this.objects[pointer] == null) {
        throw new Error('ListItemUndefined');
      }
      index = -1;
      _ref = this.items;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        item = _ref[i];
        if (item === pointer) {
          index = i;
          break;
        }
      }
      if (index === -1) {
        throw new Error('ListItemUndefined');
      }
      delete this.objects[pointer];
      return this.items.splice(index, 1);
    };

    List.prototype.removeLast = function() {
      var item;
      item = this.last();
      return this.remove(item.__POINTER__);
    };

    List.prototype.removeFirst = function() {
      var item;
      item = this.first();
      return this.remove(item.__POINTER__);
    };

    List.prototype.removeAll = function() {
      this.items = [];
      return this.objects = {};
    };

    return List;

  })();

  Iterator = (function() {
    function Iterator() {}

    Iterator.prototype.first = function() {};

    Iterator.prototype.next = function() {};

    Iterator.prototype.isDone = function() {};

    Iterator.prototype.currentItem = function() {};

    return Iterator;

  })();

  Mimosas.Iterator = ConcreteIterator = (function(_super) {
    __extends(ConcreteIterator, _super);

    function ConcreteIterator(list) {
      this.list = list;
      this.current = 0;
    }

    ConcreteIterator.prototype.first = function() {
      return this.current = 0;
    };

    ConcreteIterator.prototype.next = function() {
      return this.current += 1;
    };

    ConcreteIterator.prototype.isDone = function() {
      return this.current >= this.list.count();
    };

    ConcreteIterator.prototype.currentItem = function() {
      if (this.isDone()) {
        throw new Error("IteratorOutOfBounds");
      }
      return this.list.get(this.current);
    };

    return ConcreteIterator;

  })(Iterator);

  Aggregate = (function() {
    function Aggregate() {}

    Aggregate.prototype.createIterator = function() {};

    return Aggregate;

  })();

  Mimosas.Aggregate = ConcreteAggregate = (function(_super) {
    __extends(ConcreteAggregate, _super);

    function ConcreteAggregate() {
      _ref = ConcreteAggregate.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ConcreteAggregate.prototype.createIterator = function(items) {
      var key, list, val;
      list = new List();
      for (key in items) {
        val = items[key];
        val.__POINTER__ = key;
        list.append(val);
      }
      return new Mimosas.Iterator(list);
    };

    return ConcreteAggregate;

  })(Aggregate);

  Mimosas.Subject = Subject = (function() {
    var counter, observers;

    function Subject() {}

    counter = 0;

    observers = new Mimosas.List();

    Subject.prototype.attach = function(obj) {
      obj.__POINTER__ = this.counter;
      observers.append(obj);
      return counter += 1;
    };

    Subject.prototype.detach = function(observer) {
      return observers.remove(observer);
    };

    Subject.prototype.notify = function() {
      var i, _results;
      i = new Mimosas.Iterator(observers);
      _results = [];
      while (!i.isDone()) {
        i.currentItem().changed(this);
        _results.push(i.next());
      }
      return _results;
    };

    return Subject;

  })();

  Mimosas['extends'] = __extends;

  (function(root, factory) {
    if (typeof exports === 'object') {
      return module.exports = factory();
    } else if (typeof window.define === 'function' && window.define.amd) {
      return window.define(factory);
    } else {
      return root.Mimosas = factory();
    }
  })(this, function() {
    return Mimosas;
  });

}).call(this);
