/**
 * Mimosas v1.0.0
 * https://github.com/dustinboston/mimosas
 *
 * Copyright 2013-2014, Dustin boston
 * Released under the GPL License
 */
(function(root) {
  var Mimosas = function() {
    function require(path) { return require[path]; }

    require['./list'] = (function() {
      var exports = {}, module = {exports: exports};

      // Generated by CoffeeScript 1.6.3
      var List;

      List = (function() {
        function List() {
          this.pointers = [];
          this.items = {};
        }

        List.prototype.count = function() {
          return this.pointers.length;
        };

        List.prototype.get = function(pointer) {
          return this.items[pointer];
        };

        List.prototype.getByIndex = function(index) {
          if (index >= this.count()) {
            throw new Error('ArrayOutOfBoundsException');
          }
          if (index < 0) {
            throw new Error('ArrayOutOfBoundsException');
          }
          return this.items[this.pointers[index]];
        };

        List.prototype.first = function() {
          return this.items[this.pointers[0]];
        };

        List.prototype.last = function() {
          return this.items[this.pointers[this.pointers.length - 1]];
        };

        List.prototype.append = function(item) {
          var pointer;
          if (item.__POINTER__ == null) {
            throw new Error('NullPointerException');
          }
          pointer = item.__POINTER__;
          this.pointers.push(pointer);
          return this.items[pointer] = item;
        };

        List.prototype.remove = function(pointer) {
          var i, index, item, _i, _len, _ref;
          if (pointer == null) {
            throw new Error('ArgumentException');
          }
          if (this.items[pointer] == null) {
            throw new Error('ListItemUndefined');
          }
          index = -1;
          _ref = this.pointers;
          for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
            item = _ref[i];
            if (item === pointer) {
              index = i;
              break;
            }
          }
          if (index === -1) {
            throw new Error('ListItemUndefined');
          }
          delete this.items[pointer];
          return this.pointers.splice(index, 1);
        };

        List.prototype.removeLast = function() {
          var item;
          item = this.last();
          return this.remove(item.__POINTER__);
        };

        List.prototype.removeFirst = function() {
          var item;
          item = this.first();
          return this.remove(item.__POINTER__);
        };

        List.prototype.removeAll = function() {
          this.pointers = [];
          return this.items = {};
        };

        return List;

      })();

      exports.List = List;

      return module.exports;
    })();

    require['./iterator'] = (function() {
      var exports = {}, module = {exports: exports};

      // Generated by CoffeeScript 1.6.3
      var Iterator;

      Iterator = (function() {
        function Iterator(list) {
          this.list = list;
          this.current = 0;
        }

        Iterator.prototype.first = function() {
          this.current = 0;
          return this;
        };

        Iterator.prototype.next = function() {
          this.current += 1;
          return this;
        };

        Iterator.prototype.isDone = function() {
          return this.current >= this.list.count();
        };

        Iterator.prototype.currentItem = function() {
          if (this.isDone()) {
            throw new Error("IteratorOutOfBounds");
          }
          return this.list.getByIndex(this.current);
        };

        return Iterator;

      })();

      exports.Iterator = Iterator;

      return module.exports;
    })();

    require['./guid'] = (function() {
      var exports = {}, module = {exports: exports};

      // Generated by CoffeeScript 1.6.3
      var Guid;

      Guid = (function() {
        function Guid() {}

        Guid.generate = function() {
          var S4;
          S4 = function() {
            return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
          };
          return "" + (S4()) + (S4()) + "-" + (S4()) + "-" + (S4()) + "-" + (S4()) + "-" + (S4()) + (S4()) + (S4());
        };

        return Guid;

      })();

      exports.Guid = Guid;

      return module.exports;
    })();

    require['./model_subject'] = (function() {
      var exports = {}, module = {exports: exports};

      // Generated by CoffeeScript 1.6.3
      var Guid, Iterator, List, ModelSubject,
        __slice = [].slice;

      List = require('./list').List;

      Iterator = require('./iterator').Iterator;

      Guid = require('./guid').Guid;

      ModelSubject = (function() {
        function ModelSubject() {
          this.__POINTER__ = Guid.generate();
          this.observers = new List();
        }

        ModelSubject.prototype.attach = function(o) {
          if (o.__POINTER__ == null) {
            o.__POINTER__ = Guid.generate();
          }
          this.observers.append(o);
        };

        ModelSubject.prototype.detach = function(o) {
          this.observers.remove(o);
        };

        ModelSubject.prototype.notify = function() {
          var currentItem, i;
          i = new Iterator(this.observers);
          while (!i.isDone()) {
            currentItem = i.currentItem();
            if (currentItem.changed != null) {
              currentItem.changed.apply(currentItem, arguments);
            }
            i.next();
          }
        };

        ModelSubject.prototype.setModel = function(model) {
          this.model = model;
          return this.model.attach(this);
        };

        ModelSubject.prototype.getModel = function() {
          return this.model;
        };

        ModelSubject.prototype.changed = function() {
          var theChangedSubjectAspects;
          theChangedSubjectAspects = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        };

        return ModelSubject;

      })();

      exports.ModelSubject = ModelSubject;

      return module.exports;
    })();

    require['./controller_context'] = (function() {
      var exports = {}, module = {exports: exports};

      // Generated by CoffeeScript 1.6.3
      var ControllerContext;

      ControllerContext = (function() {
        function ControllerContext(strategy) {
          this.strategy = strategy;
          if (this.strategy == null) {
            throw new Error('ArgumentException');
          }
        }

        ControllerContext.prototype.trigger = function(method, e) {
          if (this.strategy[method] != null) {
            return this.strategy[method].call(this.strategy, e);
          }
        };

        ControllerContext.prototype.setModel = function(model) {
          return this.strategy.setModel(model);
        };

        ControllerContext.prototype.getModel = function() {
          return this.strategy.getModel();
        };

        ControllerContext.prototype.setView = function(view) {
          this.view = view;
          return this.strategy.setView(this.view);
        };

        return ControllerContext;

      })();

      exports.ControllerContext = ControllerContext;

      return module.exports;
    })();

    require['./controller_strategy'] = (function() {
      var exports = {}, module = {exports: exports};

      // Generated by CoffeeScript 1.6.3
      var ControllerStrategy;

      ControllerStrategy = (function() {
        function ControllerStrategy() {}

        ControllerStrategy.prototype.setModel = function(model) {
          this.model = model;
        };

        ControllerStrategy.prototype.getModel = function() {
          return this.model;
        };

        ControllerStrategy.prototype.setView = function(view) {
          this.view = view;
        };

        ControllerStrategy.prototype.getView = function() {
          return this.view;
        };

        return ControllerStrategy;

      })();

      exports.ControllerStrategy = ControllerStrategy;

      return module.exports;
    })();

    require['./view_observer'] = (function() {
      var exports = {}, module = {exports: exports};

      // Generated by CoffeeScript 1.6.3
      var Guid, ViewObserver,
        __slice = [].slice;

      Guid = require('./guid').Guid;

      ViewObserver = (function() {
        function ViewObserver() {
          this.__POINTER__ = Guid.generate();
        }

        ViewObserver.prototype.changed = function() {
          var theChangedSubjectAspects;
          theChangedSubjectAspects = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        };

        return ViewObserver;

      })();

      exports.ViewObserver = ViewObserver;

      return module.exports;
    })();

    require['./view_component'] = (function() {
      var exports = {}, module = {exports: exports};

      // Generated by CoffeeScript 1.6.3
      var ControllerContext, ControllerStrategy, ViewComponent, ViewObserver,
        __hasProp = {}.hasOwnProperty,
        __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

      ViewObserver = require('./view_observer').ViewObserver;

      ControllerContext = require('./controller_context').ControllerContext;

      ControllerStrategy = require('./controller_strategy').ControllerStrategy;

      ViewComponent = (function(_super) {
        __extends(ViewComponent, _super);

        ViewComponent.prototype.defaultControllerClass = ControllerStrategy;

        function ViewComponent(element) {
          this.element = element;
          ViewComponent.__super__.constructor.apply(this, arguments);
          if (!this.element) {
            throw new ReferenceError('element is not defined');
          }
          this.setController(new this.defaultControllerClass());
        }

        ViewComponent.prototype.setModel = function(model) {
          this.model = model;
          this.model.attach(this);
          return this.controller.setModel(this.model);
        };

        ViewComponent.prototype.getModel = function() {
          return this.model;
        };

        ViewComponent.prototype.setController = function(controller) {
          this.controller = new ControllerContext(controller);
          this.controller.setView(this);
          if (this.model != null) {
            return this.controller.setModel(this.model);
          }
        };

        ViewComponent.prototype.addEvent = function(type, method, selector) {
          var handler;
          handler = this.dispatchEvent.bind(this, method, selector);
          if (this.element.on) {
            return this.element.on(type, handler);
          } else if (this.element.addEventListener) {
            return this.element.addEventListener(type, handler, false);
          } else if (this.element.addListener) {
            return this.element.addListener(type, handler);
          }
        };

        ViewComponent.prototype.dispatchEvent = function(method, selector, e) {
          if (arguments.length === 3 && selector) {
            if (!this.elementMatchesSelector(e.target, selector)) {
              return;
            }
          } else if (arguments.length === 2) {
            e = selector;
          }
          return this.controller.trigger(method, e);
        };

        ViewComponent.prototype.elementMatchesSelector = function(element, selector) {
          var matches;
          matches = element.matches || element.matchesSelector || element.msMatchesSelector || element.mozMatchesSelector || element.webkitMatchesSelector || element.oMatchesSelector;
          return matches.call(element, selector);
        };

        ViewComponent.prototype.getElement = function() {
          return this.element;
        };

        ViewComponent.prototype.display = function() {
          return this.displayView();
        };

        ViewComponent.prototype.displayView = function() {
          return this.element.style.display = '';
        };

        ViewComponent.prototype.displaySuperView = function(viewPointer, callerPointer) {
          return this.callOnSuperView('displaySuperView', viewPointer, this.__POINTER__);
        };

        ViewComponent.prototype.hide = function() {
          return this.hideView();
        };

        ViewComponent.prototype.hideView = function() {
          return this.element.style.display = 'none';
        };

        ViewComponent.prototype.hideSuperView = function(viewPointer, callerPointer) {
          return this.callOnSuperView('hideSuperView', viewPointer, this.__POINTER__);
        };

        ViewComponent.prototype.release = function() {
          return this.releaseView();
        };

        ViewComponent.prototype.releaseView = function() {
          this.superView = void 0;
          return this.element.parentNode.removeChild(this.element);
        };

        ViewComponent.prototype.callOnSuperView = function(fn, viewPointer, callerPointer) {
          var _ref;
          if (((_ref = this.superView) != null ? _ref[fn] : void 0) != null) {
            return this.superView[fn](viewPointer, this.__POINTER__);
          }
        };

        ViewComponent.prototype.closest = function(element, selector) {
          var parent;
          if (element === this.element) {
            return element;
          }
          if (this.elementMatchesSelector(element, selector)) {
            return element;
          }
          parent = element.parentNode;
          return this.closest(parent, selector);
        };

        ViewComponent.prototype.getElementFromSelector = function(selector) {
          var nodes, scope;
          scope = this.element || document;
          nodes = scope.querySelectorAll(selector);
          if (nodes.length > 0) {
            return nodes[0];
          }
        };

        return ViewComponent;

      })(ViewObserver);

      exports.ViewComponent = ViewComponent;

      return module.exports;
    })();

    require['./view_composite'] = (function() {
      var exports = {}, module = {exports: exports};

      // Generated by CoffeeScript 1.6.3
      var Iterator, List, ViewComponent, ViewComposite,
        __hasProp = {}.hasOwnProperty,
        __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

      ViewComponent = require('./view_component').ViewComponent;

      List = require('./list').List;

      Iterator = require('./iterator').Iterator;

      ViewComposite = (function(_super) {
        __extends(ViewComposite, _super);

        function ViewComposite() {
          ViewComposite.__super__.constructor.apply(this, arguments);
          this.list = new List();
          this.superView = void 0;
          if (this.defaultControllerClass != null) {
            this.setController(new this.defaultControllerClass());
          }
        }

        ViewComposite.prototype.addSubView = function(component) {
          component.superView = this;
          return this.add(component);
        };

        ViewComposite.prototype.add = function(component) {
          component.superView = this;
          return this.list.append(component);
        };

        ViewComposite.prototype.remove = function(pointer) {
          return this.list.remove(pointer);
        };

        ViewComposite.prototype.display = function() {
          ViewComposite.__super__.display.apply(this, arguments);
          return this.displaySubViews();
        };

        ViewComposite.prototype.displaySubViews = function() {
          var i, subView, _results;
          i = new Mimosas.Iterator(this.list);
          _results = [];
          while (!i.isDone()) {
            subView = i.currentItem();
            subView.display();
            _results.push(i.next());
          }
          return _results;
        };

        ViewComposite.prototype.hide = function() {
          ViewComposite.__super__.hide.apply(this, arguments);
          return this.hideSubViews();
        };

        ViewComposite.prototype.hideSubViews = function() {
          var i, subView, _results;
          i = new Iterator(this.list);
          _results = [];
          while (!i.isDone()) {
            subView = i.currentItem();
            subView.hide();
            _results.push(i.next());
          }
          return _results;
        };

        ViewComposite.prototype.release = function() {
          this.releaseSubViews();
          return ViewComposite.__super__.release.apply(this, arguments);
        };

        ViewComposite.prototype.releaseSubViews = function() {
          var i, subView;
          i = new Iterator(this.list);
          while (!i.isDone()) {
            subView = i.currentItem();
            subView.release();
            i.next();
          }
          return this.list.removeAll();
        };

        return ViewComposite;

      })(ViewComponent);

      exports.ViewComposite = ViewComposite;

      return module.exports;
    })();

    require['./view_leaf'] = (function() {
      var exports = {}, module = {exports: exports};

      // Generated by CoffeeScript 1.6.3
      var ViewComponent, ViewLeaf, _ref,
        __hasProp = {}.hasOwnProperty,
        __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

      ViewComponent = require('./view_component').ViewComponent;

      ViewLeaf = (function(_super) {
        __extends(ViewLeaf, _super);

        function ViewLeaf() {
          _ref = ViewLeaf.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        return ViewLeaf;

      })(ViewComponent);

      exports.ViewLeaf = ViewLeaf;

      return module.exports;
    })();

    require['./class'] = (function() {
      var exports = {}, module = {exports: exports};

      // Generated by CoffeeScript 1.6.3
      var Class, o,
        __hasProp = {}.hasOwnProperty,
        __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

      Class = (function() {
        function Class() {}

        Class["extends"] = __extends;

        return Class;

      })();

      o = {};

      __extends(o, Object);

      exports.Class = Class;

      return module.exports;
    })();

    require['./mimosas'] = (function() {
      var exports = {}, module = {exports: exports};

      // Generated by CoffeeScript 1.6.3
      exports.VERSION = '1.0.0';

      exports.NAME = 'Mimosas';

      exports.List = require('./list').List;

      exports.Iterator = require('./iterator').Iterator;

      exports.Guid = require('./guid').Guid;

      exports.ModelSubject = require('./model_subject').ModelSubject;

      exports.ControllerContext = require('./controller_context').ControllerContext;

      exports.ControllerStrategy = require('./controller_strategy').ControllerStrategy;

      exports.ViewObserver = require('./view_observer').ViewObserver;

      exports.ViewComponent = require('./view_component').ViewComponent;

      exports.ViewComposite = require('./view_composite').ViewComposite;

      exports.ViewLeaf = require('./view_leaf').ViewLeaf;

      exports.Class = require('./class').Class;

      return module.exports;
    })();

    return require['./mimosas'];
  }();

  if (typeof define === 'function' && define.amd) {
    define(function() { return Mimosas; });
  } else if (typeof exports === 'object') {
    module.exports = Mimosas;
  } else {
    root.Mimosas = Mimosas;
  }
}(this));